### ISSUE TITLE
TaskBook.json does not save generated default new file

### ISSUE THREAD

**Issue by joyngjr** [AY2223S2-CS2103T-W13-3/tp#104]
A default TaskBook.json file is generated whenever a file is invalid. However, this newly created file cannot be found within the data folder after starting and closing the program (without running any commands). Only when we run a command (eg. add), a new json file will be created and stored.

**Comment by lywich** [comment]
I think the behavior of "write on change" is valid and should be kept as it is as it does not affect the User experience. 

For the second point the recovery step is simple (delete the save file). Will add to UG as FAQ. 

Lowered severity to low as it won't affect normal operations.
