### ISSUE TITLE
Alert command does not remove overdue deadlines

### ISSUE THREAD

**Issue by joyngjr** [AY2223S2-CS2103T-W13-3/tp#105]
1. Alert command shows a deadline that is due 2023-03-22 2348 when program is start up at 2023-03-22 2347
2. At 2023-03-22 2349, the deadline that is overdue 1 min ago is still in the alert window. 

Is this a potentially confusing behaviour since alert typically does not include overdue deadlines?

**Comment by Huggenguggen** [comment]
To clarify, the preferred behavior with reference to your first comment would be for the alert window to update in real time while it is still open? For the reloading issue, I will take a look, thanks for bringing it up.

**Comment by joyngjr** [comment]
> To clarify, the preferred behavior with reference to your first comment would be for the alert window to update in real time while it is still open? For the reloading issue, I will take a look, thanks for bringing it up.

Yep, I would think so, since it is possible for the user to keep the application continuously running, and it may not 'remind' the user in this instance. However, it's a minor issue since users can still get their reminders by re-running the command (ideally).

**Comment by joyngjr** [comment]
Clarified in UG
