### ISSUE TITLE
[PE-D][Tester B] Could not save data to file

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-3/tp#161]
I am using Windows 11, and I create a new empty folder to store the jar file. When I first launch the application, and execute the command below `add n/task D/2023-01-29 1000`.

Suggestion: Perhaps one of your members can carry out smoke test of the product in a completely new empty folder on Windows 11 OS platform in future release.

![image.png](https://raw.githubusercontent.com/jiasheng59/ped/main/files/8f5a6d84-15f6-4dbd-81ce-a79769c5b08d.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jiasheng59/ped#1

**Comment by lywich** [comment]
Hi @jiasheng59, thank you for testing our product and your comments are appreciated. 

We were wondering if you could share the folder properties of the folder that you executed this commands in. It seems like a common issue that the application is unable to save data which prohibits a few of our commands from working as intended (and its error message). 

 We hope that to replicate this bug on our systems and would like to eliminate the possibility that the jar was executed in a write-protected folder. Thanks!

**Comment by jiasheng59** [comment]
Hi @lywich , I check the properties of the folder and it's indeed read-only, but I'm not sure if it's the real cause as the folder containing my own group project for testing is also read-only but the error doesn't show up. 

```Could not save data to file: java.nio.file.AccessDeniedException: C:\WINDOWS\system32\data```
Btw, this is the full error message. 

I have also check for the folder properties of system32, it's also read-only. There's no data folder present in the folder system32.

Should you need any further clarification, please @ me in following replies. Thanks

**Comment by lywich** [comment]
Hi @jiasheng59. Thank you for the reply. Perhaps did you keep the "taskbook.log.0" from your session that you could share with us?

**Comment by jiasheng59** [comment]
@lywich There's only a jar file within the folder, the log is not found. Moreover, I found that me as a user in fact has the read & write access to the folder storing the jar file, despite the folder's read-only attribute is true.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/96868229/229987172-63b7e621-1050-471b-a19c-3aa9271ade9c.png">

**Comment by lywich** [comment]
Hi @jiasheng59 . Thank you for your reply again. We will see what we can do with this issue.

**Comment by lywich** [comment]
Exception message caused by jar file being executed in a write protected environment (System32).
