### ISSUE TITLE
[PE-D][Tester B] `stats` command is not working

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-W13-3/tp#165]
By running stats command, I don't see any difference in the change of UI. There're no statistics showing at all.

![image.png](https://raw.githubusercontent.com/jiasheng59/ped/main/files/04028616-b329-40ce-9d02-c04e0b5a90a8.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jiasheng59/ped#2

**Comment by joyngjr** [comment]
Stats is unable to display tags because of the access limitations of the folder that Clock-Work is ran in.
