### ISSUE TITLE
Change the Add Command to fit Event and Deadline

### ISSUE THREAD

**Issue by PROGRAMMERHAO** [AY2223S2-CS2103T-W13-3/tp#97]

**Comment by Huggenguggen** [comment]
I think you mean the edit command?

**Comment by Huggenguggen** [comment]
For clarification, currently the add command does support adding multiple events and deadlines. The current behavior is such that all the deadlines/events will share the same dates. I think this is intended behavior so not really a bug but maybe a future feature?
